### PR TITLE
Add AMP support

### LINKED ISSUE #57: Is this AMP compatible?
This plugin's custom modal is probably affected by the same problem as the Trust Indicators plugin, in https://github.com/INN/trust-indicators/issues/91

We could probably solve this with something like

```php
function republication_widget_if_amp_endpoint( $hide, $post ) {
   if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
       return true;
   }
   return $hide;
}
if ( function_exists( 'is_amp_endpoint' ) ) {
   add_filter( 'hide_republication_widget', 'republication_widget_if_amp_endpoint', 10, 2 );
}
```

### PR DESCRIPTION
**Pull request by adekbadek**
Adds support for AMP pages. 
Closes #57 

## How to test

1. Add the republication tracker widget as described [in the docs](https://github.com/Automattic/republication-tracker-tool/tree/master/docs)
2. Visit a post in non-AMP mode - observe everything working as before 
3. Visit a post in AMP mode - ~observe the in the widget area is the same, but after clicking the button which opens the modal, a new browser tab opens with the modal content~ observe that the modal is also shown after clicking the button, as on the non-AMP version
4. Observe that the AMP version does not sport a "Copy to clipboard" button and instead links to the original article

### CODE REVIEW

**Review by jeffersonrabb — CHANGES_REQUESTED** [review]
Is it possible to display the republication page in an iFrame using `[amp-lightbox](https://amp.dev/documentation/components/amp-lightbox/)` to come closer to matching the non-AMP implementation?

**Comment by adekbadek** [comment]
@jeffersonrabb I redid it with an AMP modal, without the need for an iframe

**Comment by adekbadek** [comment]
There's still one outstanding issue: the pixel tracking image markup gets processed by AMP, resulting in an `<amp-img>` tag.

**Comment by jeffersonrabb** [comment]
> There's still one outstanding issue: the pixel tracking image markup gets processed by AMP, resulting in an `<amp-img>` tag.

If we apply `[htmlentities](https://www.php.net/manual/en/function.htmlentities.php)` to the pixel markup, the AMP renderer won't consider it to be a valid element and will ignore. Suggested fix in https://github.com/Automattic/republication-tracker-tool/blob/5ae40466dc144a87aa6994071046093c917df54b/includes/shareable-content.php#L145-L152:

```
	echo wp_kses_post(
		sprintf(
			'<textarea readonly id="republication-tracker-tool-shareable-content" rows="5">%1$s %2$s %3$s</textarea>',
			esc_html( $article_info ),
			$content . "\n\n",
			wpautop( $attribution_statement . htmlentities( $pixel ) )
		)
	);
```

It might also make sense to encode `$attributeion_statement` just in case it happens to contain anything AMP will convert.

**Comment by adekbadek** [comment]
That works great for the `img` tag, but the attribution statement gets escaped: `This &lt;a target=&quot;_blank&quot; …`. But for the time being it's ok to just prevent AMP transformation for the image.

**Review by jeffersonrabb — APPROVED** [review]
LGTM!

**Pull request merged**
