### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by adekbadek**
### Changes proposed in this Pull Request:

Adds code formatting configuration and auto-formats existing code. 

Also, changes the `author` in package.json, adds some comments in `pixel.php`, and updated Github links.

### How to test the changes in this Pull Request:

No changes, this is a pure refactor.

### CODE REVIEW

**Review by dkoo — APPROVED** [review]
Looks good!

**Comment by dkoo** [comment]
@adekbadek Actually, there are still quite a lot of PHPCS errors and warnings when I run `phpcs` from the command line—do we want to implement CI and fix those formatting issues?

**Review by dkoo — CHANGES_REQUESTED** [review]
Still seeing PHPCS errors when I run from the command line—see comment above.

**Comment by adekbadek** [comment]
These errors are not formatting errors - this PR deals just with formatting to make further development easier. Fixing all the linting errors is a bigger job, for a future PR - alongside that, CI should be set up for linting, but now it'd just fail all the time.

**Review by dkoo — APPROVED** [review]
> Fixing all the linting errors is a bigger job, for a future PR

Ok, that sounds good, then. 👍

**Pull request merged**
